version: '3.7'

services:
  masterproject-web:
    image: mycompanyname/masterproject-web:latest
    container_name: masterproject-web
    build:
      context: ../../../
      dockerfile: angular/Dockerfile.local      
    ports:
      - "4200:80"
    depends_on:
      - masterproject-api
    volumes:
      - ./dynamic-env.json://usr/share/nginx/html/dynamic-env.json
    networks:
      - abp-network  

  masterproject-api:
    image: mycompanyname/masterproject-api:latest
    container_name: masterproject-api-container
    build:
      context: ../../
      dockerfile: MasterProject/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=8d872b07-3ba9-43d3-aa71-0d053c02b6c1
      - App__SelfUrl=https://localhost:44305
      - AuthServer__Authority=https://localhost:44305
      - AuthServer__RequireHttpsMetadata=false
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=MasterProject;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
    ports:
      - "44305:443"
    depends_on:
      sql-server:
        condition: service_healthy
    restart: on-failure    
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network  
  
  db-migrator:
    image: mycompanyname/masterproject-api:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: MasterProject/Dockerfile.local
    environment:
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=MasterProject;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - OpenIddict__Applications__MasterProject_Swagger__RootUrl=https://localhost:44305
    command:
      - --migrate-database
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network    
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network  
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  sqldata:
    name: sqldata

networks:
  abp-network:
    name: masterproject-network
    driver: bridge
