using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using MasterProject.Permissions;
using MasterProject.Contents;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using MasterProject.Shared;

namespace MasterProject.Contents
{
    public class ContentsAppService : ContentsAppServiceBase, IContentsAppService
    {
        //<suite-custom-code-autogenerated>
        public ContentsAppService(IContentRepository contentRepository, ContentManager contentManager, IDistributedCache<ContentExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(contentRepository, contentManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}