using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace MasterProject.Contents
{
    public class ContentManager : ContentManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ContentManager(IContentRepository contentRepository)
            : base(contentRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}