using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace MasterProject.Contents
{
    public class Content : ContentBase
    {
        //<suite-custom-code-autogenerated>
        protected Content()
        {

        }

        public Content(Guid id, string? name = null, string? value = null)
            : base(id, name, value)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}